on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: export timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      # Github exports the branchname in a different variable if you're on a push
      # compared to a pull_request run. These variables also require unpacking
      # because they are in /ref/head/branchname form
    - name: Git branch name
      id: git-branch-name
      uses: EthanSK/git-branch-name-action@v1
    - name: export file name
      run: echo "FILENAME=keylometer-$(echo $GIT_BRANCH_NAME | sed 's/\//-/g')-$TIMESTAMP" >> $GITHUB_ENV
    - name: Build
      run: go build -o $FILENAME
    - name: generate hash
      run: sha256sum $FILENAME > $FILENAME.sha256
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: keylometer
        path: keylometer-*
